quarkus.log.level=INFO
quarkus.banner.path=banner.txt

quarkus.cache.caffeine.expire-after-access=100s
quarkus.cache.caffeine.expire-after-write=300s

quarkus.smallrye-openapi.info-title=Cimari REST
quarkus.smallrye-openapi.info-version=0.0.1
quarkus.smallrye-openapi.info-description=Transform cimari codebase into a REST Service
quarkus.smallrye-openapi.info-contact-email=eggzerothree@proton.me
quarkus.smallrye-openapi.info-contact-name=Egg-03
quarkus.smallrye-openapi.info-license-name=MIT
quarkus.smallrye-openapi.info-license-url=https://mit-license.org/
